### ISSUE TITLE
Bug in SampleToCTS() halves available replay time

### ISSUE THREAD

**Issue by ReggThims** [roman380/gdcl.co.uk-mpeg4#41]
Line 465 in SampleToCTS() needs a cast, should be:
`            LONGLONG tThis = m_tAtBase + TrackToReftime((LONGLONG)(nSample - m_nBaseSample) * nDuration);
`
Without this change, the multiply is long * long and when you have a lot of samples this wraps around when the product reaches 2^31 (which admittedly takes a while, but I have a customer with a file that is > 1 day long!

**Comment by roman380** [comment]
This is good, thanks. I am going to merge this as this: https://github.com/roman380/gdcl.co.uk-mpeg4/pull/42

Anything else, would you build from source or you download prebuilt files?
