### ISSUE TITLE
Error in MovieWriter sets wrong time scaler in moderately long files

### ISSUE THREAD

**Issue by ReggThims** [roman380/gdcl.co.uk-mpeg4#44]
In MoveiWriter.cpp line 573 in TrackWriter::Close() you have the line:
`    LONGLONG scaledur = long(Duration() * m_pMovie->MovieScale() / UNITS);`
This has unfortunate effects when (with MovieScale() set to 360000) Duration() reaches 6000 seconds (6x10^10 in REFERENCE_TIME) as the cast to long truncates the value - or makes it negative. The fix is to remove the `long(...)` cast to match line 68:
`    LONGLONG scaledur = Duration() * m_pMovie->MovieScale() / UNITS;`

**Comment by roman380** [comment]
I fixed this and the other one, thanks!
